#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=scripts/lib/runtime.sh
source "${REPO_ROOT}/scripts/lib/runtime.sh"

profile_override=""
root_override=""
compose_project_override=""
network_override=""
egress_network_override=""
ollama_models_override=""
non_interactive=0
output_file="${AGENTIC_ONBOARD_OUTPUT:-${AGENTIC_REPO_ROOT}/.runtime/env.generated.sh}"

usage() {
  cat <<'USAGE'
Usage:
  deployments/bootstrap/onboarding_env.sh [options]

Options:
  --profile <strict-prod|rootless-dev>
  --root <path>
  --compose-project <name>
  --network <name>
  --egress-network <name>
  --ollama-models-dir <path>
  --output <path>
  --non-interactive
  -h, --help
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

warn() {
  echo "WARN: $*" >&2
}

info() {
  echo "INFO: $*"
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\"'\"'/g")"
}

default_root_for_profile() {
  local profile="$1"
  if [[ "${profile}" == "rootless-dev" ]]; then
    printf '%s\n' "${HOME}/.local/share/agentic"
  else
    printf '%s\n' "/srv/agentic"
  fi
}

default_compose_project_for_profile() {
  local profile="$1"
  if [[ "${profile}" == "rootless-dev" ]]; then
    printf '%s\n' "agentic-dev"
  else
    printf '%s\n' "agentic"
  fi
}

default_network_for_profile() {
  local profile="$1"
  if [[ "${profile}" == "rootless-dev" ]]; then
    printf '%s\n' "agentic-dev"
  else
    printf '%s\n' "agentic"
  fi
}

default_egress_network_for_profile() {
  local profile="$1"
  if [[ "${profile}" == "rootless-dev" ]]; then
    printf '%s\n' "agentic-dev-egress"
  else
    printf '%s\n' "agentic-egress"
  fi
}

default_ollama_models_for_profile() {
  local profile="$1"
  local root_path="$2"
  if [[ "${profile}" == "rootless-dev" ]]; then
    printf '%s\n' "${AGENTIC_REPO_ROOT}/.runtime/ollama-models"
  else
    printf '%s\n' "${root_path}/ollama/models"
  fi
}

validate_profile() {
  case "$1" in
    strict-prod|rootless-dev) return 0 ;;
    *) return 1 ;;
  esac
}

validate_compose_or_network_name() {
  local key="$1"
  local value="$2"
  [[ -n "${value}" ]] || {
    echo "${key} cannot be empty" >&2
    return 1
  }
  [[ "${value}" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] || {
    echo "${key} must match [a-zA-Z0-9][a-zA-Z0-9_.-]*" >&2
    return 1
  }
}

validate_path_value() {
  local profile="$1"
  local key="$2"
  local value="$3"
  local parent=""

  [[ -n "${value}" ]] || {
    echo "${key} cannot be empty" >&2
    return 1
  }
  [[ "${value}" != *$'\n'* ]] || {
    echo "${key} must be a single-line path" >&2
    return 1
  }
  [[ "${value}" == /* ]] || {
    echo "${key} must be an absolute path (start with /)" >&2
    return 1
  }
  [[ "${value}" != *[[:space:]]* ]] || {
    echo "${key} should not include spaces" >&2
    return 1
  }

  if [[ -e "${value}" ]]; then
    [[ -d "${value}" ]] || {
      echo "${key} exists but is not a directory: ${value}" >&2
      return 1
    }
    return 0
  fi

  parent="${value}"
  while [[ "${parent}" != "/" && ! -d "${parent}" ]]; do
    parent="$(dirname "${parent}")"
  done

  if [[ -w "${parent}" ]]; then
    return 0
  fi

  if [[ "${profile}" == "strict-prod" ]]; then
    warn "${key} parent '${parent}' is not writable for current user; this is acceptable in strict-prod when running setup with sudo later."
    return 0
  fi

  echo "${key} is not creatable from current user context (parent not writable: ${parent}). Choose another path or fix permissions." >&2
  return 1
}

prompt_with_default() {
  local prompt="$1"
  local default_value="$2"
  local value=""

  printf '%s [%s]: ' "${prompt}" "${default_value}" >&2
  IFS= read -r value || die "input aborted"
  if [[ -z "${value}" ]]; then
    value="${default_value}"
  fi
  printf '%s\n' "${value}"
}

normalize_output_path() {
  if [[ "${output_file}" != /* ]]; then
    output_file="${AGENTIC_REPO_ROOT}/${output_file}"
  fi
}

write_env_file() {
  local profile="$1"
  local root_path="$2"
  local compose_project="$3"
  local network="$4"
  local egress_network="$5"
  local ollama_models="$6"
  local out_file="$7"
  local tmp_file=""

  install -d -m 0750 "$(dirname "${out_file}")"
  tmp_file="$(mktemp "${out_file}.tmp.XXXXXX")"
  cat >"${tmp_file}" <<EOF
#!/usr/bin/env bash
# Generated by deployments/bootstrap/onboarding_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source this file in your shell to set runtime variables.
export AGENTIC_PROFILE=$(shell_quote "${profile}")
export AGENTIC_ROOT=$(shell_quote "${root_path}")
export AGENTIC_COMPOSE_PROJECT=$(shell_quote "${compose_project}")
export AGENTIC_NETWORK=$(shell_quote "${network}")
export AGENTIC_EGRESS_NETWORK=$(shell_quote "${egress_network}")
export OLLAMA_MODELS_DIR=$(shell_quote "${ollama_models}")
EOF
  mv "${tmp_file}" "${out_file}"
  chmod 0640 "${out_file}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      [[ $# -ge 2 ]] || die "missing value for --profile"
      profile_override="$2"
      shift 2
      ;;
    --root)
      [[ $# -ge 2 ]] || die "missing value for --root"
      root_override="$2"
      shift 2
      ;;
    --compose-project)
      [[ $# -ge 2 ]] || die "missing value for --compose-project"
      compose_project_override="$2"
      shift 2
      ;;
    --network)
      [[ $# -ge 2 ]] || die "missing value for --network"
      network_override="$2"
      shift 2
      ;;
    --egress-network)
      [[ $# -ge 2 ]] || die "missing value for --egress-network"
      egress_network_override="$2"
      shift 2
      ;;
    --ollama-models-dir)
      [[ $# -ge 2 ]] || die "missing value for --ollama-models-dir"
      ollama_models_override="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || die "missing value for --output"
      output_file="$2"
      shift 2
      ;;
    --non-interactive)
      non_interactive=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

normalize_output_path

profile="${profile_override:-${AGENTIC_PROFILE}}"
if [[ "${non_interactive}" -eq 0 && -z "${profile_override}" ]]; then
  info "AGENTIC_PROFILE controls host mode: strict-prod (target CDC) or rootless-dev (local dev)."
  while true; do
    candidate="$(prompt_with_default "AGENTIC_PROFILE (strict-prod or rootless-dev)" "${profile}")"
    if validate_profile "${candidate}"; then
      profile="${candidate}"
      break
    fi
    echo "Invalid profile '${candidate}'. Allowed values: strict-prod or rootless-dev." >&2
  done
fi
validate_profile "${profile}" || die "invalid profile '${profile}' (expected strict-prod or rootless-dev)"

default_root="$(default_root_for_profile "${profile}")"
default_compose_project="$(default_compose_project_for_profile "${profile}")"
default_network="$(default_network_for_profile "${profile}")"
default_egress_network="$(default_egress_network_for_profile "${profile}")"

root_path="${root_override:-${default_root}}"
if [[ "${non_interactive}" -eq 0 && -z "${root_override}" ]]; then
  info "AGENTIC_ROOT is where persistent runtime folders are stored."
  while true; do
    candidate="$(prompt_with_default "AGENTIC_ROOT" "${root_path}")"
    if validate_path_value "${profile}" "AGENTIC_ROOT" "${candidate}"; then
      root_path="${candidate}"
      break
    fi
  done
else
  validate_path_value "${profile}" "AGENTIC_ROOT" "${root_path}" || die "invalid AGENTIC_ROOT"
fi

compose_project="${compose_project_override:-${default_compose_project}}"
if [[ "${non_interactive}" -eq 0 && -z "${compose_project_override}" ]]; then
  info "AGENTIC_COMPOSE_PROJECT is the docker compose project name used to namespace containers."
  while true; do
    candidate="$(prompt_with_default "AGENTIC_COMPOSE_PROJECT" "${compose_project}")"
    if validate_compose_or_network_name "AGENTIC_COMPOSE_PROJECT" "${candidate}"; then
      compose_project="${candidate}"
      break
    fi
  done
else
  validate_compose_or_network_name "AGENTIC_COMPOSE_PROJECT" "${compose_project}" || die "invalid AGENTIC_COMPOSE_PROJECT"
fi

network="${network_override:-${default_network}}"
if [[ "${non_interactive}" -eq 0 && -z "${network_override}" ]]; then
  info "AGENTIC_NETWORK is the private internal docker network for services."
  while true; do
    candidate="$(prompt_with_default "AGENTIC_NETWORK" "${network}")"
    if validate_compose_or_network_name "AGENTIC_NETWORK" "${candidate}"; then
      network="${candidate}"
      break
    fi
  done
else
  validate_compose_or_network_name "AGENTIC_NETWORK" "${network}" || die "invalid AGENTIC_NETWORK"
fi

egress_network="${egress_network_override:-${default_egress_network}}"
if [[ "${non_interactive}" -eq 0 && -z "${egress_network_override}" ]]; then
  info "AGENTIC_EGRESS_NETWORK is the dedicated docker network for controlled outbound traffic."
  while true; do
    candidate="$(prompt_with_default "AGENTIC_EGRESS_NETWORK" "${egress_network}")"
    if validate_compose_or_network_name "AGENTIC_EGRESS_NETWORK" "${candidate}"; then
      egress_network="${candidate}"
      break
    fi
  done
else
  validate_compose_or_network_name "AGENTIC_EGRESS_NETWORK" "${egress_network}" || die "invalid AGENTIC_EGRESS_NETWORK"
fi

default_ollama_models="$(default_ollama_models_for_profile "${profile}" "${root_path}")"
ollama_models="${ollama_models_override:-${default_ollama_models}}"
if [[ "${non_interactive}" -eq 0 && -z "${ollama_models_override}" ]]; then
  info "OLLAMA_MODELS_DIR points to the shared Ollama model store path on the host."
  while true; do
    candidate="$(prompt_with_default "OLLAMA_MODELS_DIR" "${ollama_models}")"
    if validate_path_value "${profile}" "OLLAMA_MODELS_DIR" "${candidate}"; then
      ollama_models="${candidate}"
      break
    fi
  done
else
  validate_path_value "${profile}" "OLLAMA_MODELS_DIR" "${ollama_models}" || die "invalid OLLAMA_MODELS_DIR"
fi

write_env_file \
  "${profile}" \
  "${root_path}" \
  "${compose_project}" \
  "${network}" \
  "${egress_network}" \
  "${ollama_models}" \
  "${output_file}"

if command -v git >/dev/null 2>&1 && git -C "${AGENTIC_REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  rel_output="${output_file#${AGENTIC_REPO_ROOT}/}"
  if ! git -C "${AGENTIC_REPO_ROOT}" check-ignore -q "${rel_output}" 2>/dev/null; then
    warn "generated file is not git-ignored: ${output_file}"
  fi
fi

info "environment file generated: ${output_file}"
echo
echo "Run the following commands:"
echo "  source \"${output_file}\""
echo "  ./agent profile"
