#!/usr/bin/env bash
set -euo pipefail

# Initialize n8n runtime environment
# This script creates the necessary directory structure and configuration
# for the n8n service to run with proper permissions.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source runtime environment
# shellcheck source=scripts/lib/runtime.sh
source "${REPO_ROOT}/scripts/lib/runtime.sh"

echo "Initializing n8n runtime environment..."

# Create directory structure
N8N_BASE_DIR="${AGENTIC_ROOT:-/srv/agentic}/optional/n8n"

mkdir -p "${N8N_BASE_DIR}/data"
mkdir -p "${N8N_BASE_DIR}/config"
mkdir -p "${N8N_BASE_DIR}/custom"
mkdir -p "${N8N_BASE_DIR}/logs"

# Set permissions (readable by runtime user)
chmod 750 "${N8N_BASE_DIR}"
chmod 750 "${N8N_BASE_DIR}/data"
chmod 750 "${N8N_BASE_DIR}/config"
chmod 750 "${N8N_BASE_DIR}/custom"
chmod 750 "${N8N_BASE_DIR}/logs"

# Create default configuration if it doesn't exist
N8N_CONFIG_FILE="${N8N_BASE_DIR}/config/default.json"
if [ ! -f "${N8N_CONFIG_FILE}" ]; then
    cat > "${N8N_CONFIG_FILE}" << 'EOF'
{
  "database": {
    "type": "sqlite",
    "path": "/home/node/.n8n/database.sqlite"
  },
  "workflows": {
    "path": "/home/node/.n8n/workflows"
  },
  "credentials": {
    "path": "/home/node/.n8n/credentials"
  },
  "global": {
    "timezone": "UTC"
  }
}
EOF
    chmod 640 "${N8N_CONFIG_FILE}"
fi

# Create environment file if it doesn't exist
N8N_ENV_FILE="${N8N_BASE_DIR}/config/n8n.env"
if [ ! -f "${N8N_ENV_FILE}" ]; then
    cat > "${N8N_ENV_FILE}" << EOF
# n8n Environment Configuration
# Generated by init_n8n_runtime.sh

# Basic Authentication
N8N_BASIC_AUTH_ACTIVE=true
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASSWORD=change-me

# Server Configuration
N8N_HOST=0.0.0.0
N8N_PORT=5678
N8N_PROTOCOL=http

# Logging
NODE_ENV=production
N8N_LOG_LEVEL=info
N8N_LOG_OUTPUT=console

# Performance
N8N_MAX_MEMORY_USAGE=1024
EOF
    chmod 640 "${N8N_ENV_FILE}"
fi

# Set ownership if running as root
if [ "$(id -u)" = "0" ]; then
    chown -R "${AGENT_RUNTIME_UID:-1000}:${AGENT_RUNTIME_GID:-1000}" "${N8N_BASE_DIR}"
    echo "Set ownership to ${AGENT_RUNTIME_UID:-1000}:${AGENT_RUNTIME_GID:-1000}"
else
    echo "Not running as root, skipping ownership change"
fi

echo "n8n runtime initialized successfully in ${N8N_BASE_DIR}"
echo "To start n8n, use: agent up optional --profile optional-n8n"