#!/usr/bin/env bash

agentic_repo_root() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "${script_dir}/../.." && pwd
}

AGENTIC_REPO_ROOT="$(agentic_repo_root)"
AGENTIC_PROFILE="${AGENTIC_PROFILE:-strict-prod}"

case "${AGENTIC_PROFILE}" in
  strict-prod|rootless-dev)
    ;;
  *)
    echo "ERROR: invalid AGENTIC_PROFILE='${AGENTIC_PROFILE}' (expected strict-prod or rootless-dev)" >&2
    return 1 2>/dev/null || exit 1
    ;;
esac

if [[ "${AGENTIC_PROFILE}" == "rootless-dev" ]]; then
  AGENTIC_ROOT="${AGENTIC_ROOT:-${HOME}/.local/share/agentic}"
  AGENTIC_AGENT_WORKSPACES_ROOT="${AGENTIC_AGENT_WORKSPACES_ROOT:-${AGENTIC_ROOT}/agent-workspaces}"
  AGENTIC_COMPOSE_PROJECT="${AGENTIC_COMPOSE_PROJECT:-agentic-dev}"
  AGENTIC_NETWORK="${AGENTIC_NETWORK:-agentic-dev}"
  AGENTIC_LLM_NETWORK="${AGENTIC_LLM_NETWORK:-agentic-dev-llm}"
  AGENTIC_EGRESS_NETWORK="${AGENTIC_EGRESS_NETWORK:-agentic-dev-egress}"
  AGENTIC_DOCKER_USER_SOURCE_NETWORKS="${AGENTIC_DOCKER_USER_SOURCE_NETWORKS:-${AGENTIC_NETWORK},${AGENTIC_EGRESS_NETWORK}}"
  AGENTIC_DOCKER_USER_CHAIN="${AGENTIC_DOCKER_USER_CHAIN:-AGENTIC-DOCKER-USER}"
  AGENT_RUNTIME_UID="${AGENT_RUNTIME_UID:-$(id -u)}"
  AGENT_RUNTIME_GID="${AGENT_RUNTIME_GID:-$(id -g)}"
  QDRANT_CONTAINER_USER="${QDRANT_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GATE_CONTAINER_USER="${GATE_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  AGENTIC_OLLAMA_MODELS_LINK="${AGENTIC_OLLAMA_MODELS_LINK:-${AGENTIC_REPO_ROOT}/.runtime/ollama-models}"
  OLLAMA_CONTAINER_USER="${OLLAMA_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  PROMETHEUS_CONTAINER_USER="${PROMETHEUS_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GRAFANA_CONTAINER_USER="${GRAFANA_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  LOKI_CONTAINER_USER="${LOKI_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  PROMTAIL_CONTAINER_USER="${PROMTAIL_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  TRTLLM_CONTAINER_USER="${TRTLLM_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"

  AGENTIC_SKIP_DOCKER_USER_APPLY="${AGENTIC_SKIP_DOCKER_USER_APPLY:-1}"
  AGENTIC_SKIP_DOCKER_USER_CHECK="${AGENTIC_SKIP_DOCKER_USER_CHECK:-1}"
  AGENTIC_SKIP_DOCTOR_PROXY_CHECK="${AGENTIC_SKIP_DOCTOR_PROXY_CHECK:-1}"
else
  AGENTIC_ROOT="${AGENTIC_ROOT:-/srv/agentic}"
  AGENTIC_AGENT_WORKSPACES_ROOT="${AGENTIC_AGENT_WORKSPACES_ROOT:-${AGENTIC_ROOT}}"
  AGENTIC_COMPOSE_PROJECT="${AGENTIC_COMPOSE_PROJECT:-agentic}"
  AGENTIC_NETWORK="${AGENTIC_NETWORK:-agentic}"
  AGENTIC_LLM_NETWORK="${AGENTIC_LLM_NETWORK:-agentic-llm}"
  AGENTIC_EGRESS_NETWORK="${AGENTIC_EGRESS_NETWORK:-agentic-egress}"
  AGENTIC_DOCKER_USER_SOURCE_NETWORKS="${AGENTIC_DOCKER_USER_SOURCE_NETWORKS:-${AGENTIC_NETWORK},${AGENTIC_EGRESS_NETWORK}}"
  AGENTIC_DOCKER_USER_CHAIN="${AGENTIC_DOCKER_USER_CHAIN:-AGENTIC-DOCKER-USER}"
  AGENT_RUNTIME_UID="${AGENT_RUNTIME_UID:-1000}"
  AGENT_RUNTIME_GID="${AGENT_RUNTIME_GID:-1000}"
  QDRANT_CONTAINER_USER="${QDRANT_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GATE_CONTAINER_USER="${GATE_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  AGENTIC_OLLAMA_MODELS_LINK="${AGENTIC_OLLAMA_MODELS_LINK:-${AGENTIC_REPO_ROOT}/.runtime/ollama-models}"
  # Ollama keeps root by default in strict-prod because the upstream image expects /root/.ollama.
  OLLAMA_CONTAINER_USER="${OLLAMA_CONTAINER_USER:-0:0}"
  PROMETHEUS_CONTAINER_USER="${PROMETHEUS_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GRAFANA_CONTAINER_USER="${GRAFANA_CONTAINER_USER:-472:472}"
  LOKI_CONTAINER_USER="${LOKI_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  # Promtail keeps root by default to read host Docker/container logs in strict-prod.
  PROMTAIL_CONTAINER_USER="${PROMTAIL_CONTAINER_USER:-0:0}"
  TRTLLM_CONTAINER_USER="${TRTLLM_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
fi

AGENTIC_CLAUDE_WORKSPACES_DIR="${AGENTIC_CLAUDE_WORKSPACES_DIR:-${AGENTIC_AGENT_WORKSPACES_ROOT}/claude/workspaces}"
AGENTIC_CODEX_WORKSPACES_DIR="${AGENTIC_CODEX_WORKSPACES_DIR:-${AGENTIC_AGENT_WORKSPACES_ROOT}/codex/workspaces}"
AGENTIC_OPENCODE_WORKSPACES_DIR="${AGENTIC_OPENCODE_WORKSPACES_DIR:-${AGENTIC_AGENT_WORKSPACES_ROOT}/opencode/workspaces}"
AGENTIC_VIBESTRAL_WORKSPACES_DIR="${AGENTIC_VIBESTRAL_WORKSPACES_DIR:-${AGENTIC_AGENT_WORKSPACES_ROOT}/vibestral/workspaces}"
AGENTIC_OPENHANDS_WORKSPACES_DIR="${AGENTIC_OPENHANDS_WORKSPACES_DIR:-${AGENTIC_ROOT}/openhands/workspaces}"

AGENTIC_COMPOSE_DIR="${AGENTIC_COMPOSE_DIR:-${AGENTIC_REPO_ROOT}/compose}"
AGENTIC_TEST_DIR="${AGENTIC_TEST_DIR:-${AGENTIC_REPO_ROOT}/tests}"
AGENTIC_AGENT_BASE_BUILD_CONTEXT="${AGENTIC_AGENT_BASE_BUILD_CONTEXT:-${AGENTIC_REPO_ROOT}}"
AGENTIC_AGENT_BASE_DOCKERFILE="${AGENTIC_AGENT_BASE_DOCKERFILE:-${AGENTIC_REPO_ROOT}/deployments/images/agent-cli-base/Dockerfile}"
AGENTIC_AGENT_BASE_IMAGE="${AGENTIC_AGENT_BASE_IMAGE:-agentic/agent-cli-base:local}"
AGENTIC_AGENT_CLI_INSTALL_MODE="${AGENTIC_AGENT_CLI_INSTALL_MODE:-best-effort}"
AGENTIC_AGENT_NO_NEW_PRIVILEGES="${AGENTIC_AGENT_NO_NEW_PRIVILEGES:-true}"
case "${AGENTIC_AGENT_NO_NEW_PRIVILEGES}" in
  true|false) ;;
  *)
    echo "WARN: invalid AGENTIC_AGENT_NO_NEW_PRIVILEGES='${AGENTIC_AGENT_NO_NEW_PRIVILEGES}', defaulting to true" >&2
    AGENTIC_AGENT_NO_NEW_PRIVILEGES="true"
    ;;
esac
AGENTIC_CODEX_CLI_NPM_SPEC="${AGENTIC_CODEX_CLI_NPM_SPEC:-@openai/codex@latest}"
AGENTIC_CLAUDE_CODE_NPM_SPEC="${AGENTIC_CLAUDE_CODE_NPM_SPEC:-@anthropic-ai/claude-code@latest}"
AGENTIC_OPENCODE_NPM_SPEC="${AGENTIC_OPENCODE_NPM_SPEC:-opencode-ai@latest}"
AGENTIC_PI_CODING_AGENT_NPM_SPEC="${AGENTIC_PI_CODING_AGENT_NPM_SPEC:-@mariozechner/pi-coding-agent@latest}"
AGENTIC_OPENHANDS_INSTALL_SCRIPT="${AGENTIC_OPENHANDS_INSTALL_SCRIPT:-https://install.openhands.dev/install.sh}"
AGENTIC_OPENCLAW_INSTALL_CLI_SCRIPT="${AGENTIC_OPENCLAW_INSTALL_CLI_SCRIPT:-https://openclaw.ai/install-cli.sh}"
AGENTIC_OPENCLAW_INSTALL_VERSION="${AGENTIC_OPENCLAW_INSTALL_VERSION:-latest}"
AGENTIC_VIBE_INSTALL_SCRIPT="${AGENTIC_VIBE_INSTALL_SCRIPT:-https://mistral.ai/vibe/install.sh}"

if [[ "${AGENTIC_AGENT_BASE_BUILD_CONTEXT}" != /* ]]; then
  AGENTIC_AGENT_BASE_BUILD_CONTEXT="${AGENTIC_REPO_ROOT}/${AGENTIC_AGENT_BASE_BUILD_CONTEXT}"
fi
if [[ "${AGENTIC_AGENT_BASE_DOCKERFILE}" != /* ]]; then
  AGENTIC_AGENT_BASE_DOCKERFILE="${AGENTIC_REPO_ROOT}/${AGENTIC_AGENT_BASE_DOCKERFILE}"
fi

if [[ "${AGENTIC_PROFILE}" == "rootless-dev" ]]; then
  OLLAMA_MODELS_DIR="${OLLAMA_MODELS_DIR:-${AGENTIC_OLLAMA_MODELS_LINK}}"
  OLLAMA_CONTAINER_MODELS_PATH="${OLLAMA_CONTAINER_MODELS_PATH:-/tmp/ollama/models}"
else
  OLLAMA_MODELS_DIR="${OLLAMA_MODELS_DIR:-${AGENTIC_ROOT}/ollama/models}"
  OLLAMA_CONTAINER_MODELS_PATH="${OLLAMA_CONTAINER_MODELS_PATH:-/root/.ollama/models}"
fi
OLLAMA_MODELS_MOUNT_MODE="${OLLAMA_MODELS_MOUNT_MODE:-rw}"
AGENTIC_DEFAULT_MODEL="${AGENTIC_DEFAULT_MODEL:-qwen3-coder:30b}"
AGENTIC_DEFAULT_MODEL_CONTEXT_WINDOW="${AGENTIC_DEFAULT_MODEL_CONTEXT_WINDOW:-262144}"
AGENTIC_GOOSE_CONTEXT_LIMIT="${AGENTIC_GOOSE_CONTEXT_LIMIT:-${AGENTIC_DEFAULT_MODEL_CONTEXT_WINDOW}}"
OLLAMA_PRELOAD_GENERATE_MODEL="${OLLAMA_PRELOAD_GENERATE_MODEL:-${AGENTIC_DEFAULT_MODEL}}"
OLLAMA_PRELOAD_EMBED_MODEL="${OLLAMA_PRELOAD_EMBED_MODEL:-qwen3-embedding:0.6b}"
OLLAMA_MODEL_STORE_BUDGET_GB="${OLLAMA_MODEL_STORE_BUDGET_GB:-32}"
RAG_EMBED_MODEL="${RAG_EMBED_MODEL:-qwen3-embedding:0.6b}"
OLLAMA_CONTEXT_LENGTH="${OLLAMA_CONTEXT_LENGTH:-${AGENTIC_DEFAULT_MODEL_CONTEXT_WINDOW}}"
AGENTIC_LLM_MODE="${AGENTIC_LLM_MODE:-hybrid}"
case "${AGENTIC_LLM_MODE}" in
  local|hybrid|remote) ;;
  *)
    echo "WARN: invalid AGENTIC_LLM_MODE='${AGENTIC_LLM_MODE}', defaulting to hybrid" >&2
    AGENTIC_LLM_MODE="hybrid"
    ;;
esac
GATE_ENABLE_TEST_MODE="${GATE_ENABLE_TEST_MODE:-0}"
case "${GATE_ENABLE_TEST_MODE}" in
  1|true|TRUE|yes|YES|on|ON)
    GATE_ENABLE_TEST_MODE="1"
    ;;
  0|false|FALSE|no|NO|off|OFF|"")
    GATE_ENABLE_TEST_MODE="0"
    ;;
  *)
    echo "WARN: invalid GATE_ENABLE_TEST_MODE='${GATE_ENABLE_TEST_MODE}', defaulting to 0" >&2
    GATE_ENABLE_TEST_MODE="0"
    ;;
esac
AGENTIC_OPENAI_DAILY_TOKENS="${AGENTIC_OPENAI_DAILY_TOKENS:-0}"
AGENTIC_OPENAI_MONTHLY_TOKENS="${AGENTIC_OPENAI_MONTHLY_TOKENS:-0}"
AGENTIC_OPENAI_DAILY_REQUESTS="${AGENTIC_OPENAI_DAILY_REQUESTS:-0}"
AGENTIC_OPENAI_MONTHLY_REQUESTS="${AGENTIC_OPENAI_MONTHLY_REQUESTS:-0}"
AGENTIC_OPENROUTER_DAILY_TOKENS="${AGENTIC_OPENROUTER_DAILY_TOKENS:-0}"
AGENTIC_OPENROUTER_MONTHLY_TOKENS="${AGENTIC_OPENROUTER_MONTHLY_TOKENS:-0}"
AGENTIC_OPENROUTER_DAILY_REQUESTS="${AGENTIC_OPENROUTER_DAILY_REQUESTS:-0}"
AGENTIC_OPENROUTER_MONTHLY_REQUESTS="${AGENTIC_OPENROUTER_MONTHLY_REQUESTS:-0}"
GATE_MCP_RATE_LIMIT_RPS="${GATE_MCP_RATE_LIMIT_RPS:-5}"
GATE_MCP_RATE_LIMIT_BURST="${GATE_MCP_RATE_LIMIT_BURST:-10}"
GATE_MCP_HTTP_TIMEOUT_SEC="${GATE_MCP_HTTP_TIMEOUT_SEC:-5}"
GATE_MCP_ALLOWED_MODEL_REGEX="${GATE_MCP_ALLOWED_MODEL_REGEX:-}"
PROMTAIL_DOCKER_CONTAINERS_HOST_PATH="${PROMTAIL_DOCKER_CONTAINERS_HOST_PATH:-/var/lib/docker/containers}"
PROMTAIL_HOST_LOG_PATH="${PROMTAIL_HOST_LOG_PATH:-/var/log}"
NODE_EXPORTER_HOST_ROOT_PATH="${NODE_EXPORTER_HOST_ROOT_PATH:-/}"
CADVISOR_HOST_ROOT_PATH="${CADVISOR_HOST_ROOT_PATH:-/}"
CADVISOR_DOCKER_LIB_HOST_PATH="${CADVISOR_DOCKER_LIB_HOST_PATH:-/var/lib/docker}"
CADVISOR_SYS_HOST_PATH="${CADVISOR_SYS_HOST_PATH:-/sys}"
CADVISOR_DEV_DISK_HOST_PATH="${CADVISOR_DEV_DISK_HOST_PATH:-/dev/disk}"
if [[ "${AGENTIC_PROFILE}" == "rootless-dev" ]]; then
  AGENTIC_LIMIT_DEFAULT_CPUS="${AGENTIC_LIMIT_DEFAULT_CPUS:-0.75}"
  AGENTIC_LIMIT_DEFAULT_MEM="${AGENTIC_LIMIT_DEFAULT_MEM:-1g}"
  AGENTIC_LIMIT_CORE_CPUS="${AGENTIC_LIMIT_CORE_CPUS:-1.00}"
  AGENTIC_LIMIT_CORE_MEM="${AGENTIC_LIMIT_CORE_MEM:-2g}"
  AGENTIC_LIMIT_OLLAMA_MEM="${AGENTIC_LIMIT_OLLAMA_MEM:-64g}"
  AGENTIC_LIMIT_AGENTS_CPUS="${AGENTIC_LIMIT_AGENTS_CPUS:-0.75}"
  AGENTIC_LIMIT_AGENTS_MEM="${AGENTIC_LIMIT_AGENTS_MEM:-1g}"
  AGENTIC_LIMIT_UI_CPUS="${AGENTIC_LIMIT_UI_CPUS:-0.75}"
  AGENTIC_LIMIT_UI_MEM="${AGENTIC_LIMIT_UI_MEM:-1g}"
  AGENTIC_LIMIT_OPENHANDS_MEM="${AGENTIC_LIMIT_OPENHANDS_MEM:-2g}"
  AGENTIC_LIMIT_COMFYUI_MEM="${AGENTIC_LIMIT_COMFYUI_MEM:-4g}"
  AGENTIC_LIMIT_OBS_CPUS="${AGENTIC_LIMIT_OBS_CPUS:-0.50}"
  AGENTIC_LIMIT_OBS_MEM="${AGENTIC_LIMIT_OBS_MEM:-512m}"
  AGENTIC_LIMIT_RAG_CPUS="${AGENTIC_LIMIT_RAG_CPUS:-0.75}"
  AGENTIC_LIMIT_RAG_MEM="${AGENTIC_LIMIT_RAG_MEM:-1g}"
  AGENTIC_LIMIT_OPTIONAL_CPUS="${AGENTIC_LIMIT_OPTIONAL_CPUS:-0.50}"
  AGENTIC_LIMIT_OPTIONAL_MEM="${AGENTIC_LIMIT_OPTIONAL_MEM:-512m}"
else
  AGENTIC_LIMIT_DEFAULT_CPUS="${AGENTIC_LIMIT_DEFAULT_CPUS:-1.00}"
  AGENTIC_LIMIT_DEFAULT_MEM="${AGENTIC_LIMIT_DEFAULT_MEM:-1g}"
  AGENTIC_LIMIT_CORE_CPUS="${AGENTIC_LIMIT_CORE_CPUS:-1.50}"
  AGENTIC_LIMIT_CORE_MEM="${AGENTIC_LIMIT_CORE_MEM:-3g}"
  AGENTIC_LIMIT_OLLAMA_MEM="${AGENTIC_LIMIT_OLLAMA_MEM:-96g}"
  AGENTIC_LIMIT_AGENTS_CPUS="${AGENTIC_LIMIT_AGENTS_CPUS:-1.00}"
  AGENTIC_LIMIT_AGENTS_MEM="${AGENTIC_LIMIT_AGENTS_MEM:-2g}"
  AGENTIC_LIMIT_UI_CPUS="${AGENTIC_LIMIT_UI_CPUS:-1.00}"
  AGENTIC_LIMIT_UI_MEM="${AGENTIC_LIMIT_UI_MEM:-2g}"
  AGENTIC_LIMIT_OPENHANDS_MEM="${AGENTIC_LIMIT_OPENHANDS_MEM:-4g}"
  AGENTIC_LIMIT_COMFYUI_MEM="${AGENTIC_LIMIT_COMFYUI_MEM:-8g}"
  AGENTIC_LIMIT_OBS_CPUS="${AGENTIC_LIMIT_OBS_CPUS:-0.75}"
  AGENTIC_LIMIT_OBS_MEM="${AGENTIC_LIMIT_OBS_MEM:-1g}"
  AGENTIC_LIMIT_RAG_CPUS="${AGENTIC_LIMIT_RAG_CPUS:-1.00}"
  AGENTIC_LIMIT_RAG_MEM="${AGENTIC_LIMIT_RAG_MEM:-2g}"
  AGENTIC_LIMIT_OPTIONAL_CPUS="${AGENTIC_LIMIT_OPTIONAL_CPUS:-0.75}"
  AGENTIC_LIMIT_OPTIONAL_MEM="${AGENTIC_LIMIT_OPTIONAL_MEM:-1g}"
fi

export AGENTIC_REPO_ROOT AGENTIC_PROFILE
export AGENTIC_ROOT AGENTIC_AGENT_WORKSPACES_ROOT AGENTIC_CLAUDE_WORKSPACES_DIR AGENTIC_CODEX_WORKSPACES_DIR AGENTIC_OPENCODE_WORKSPACES_DIR AGENTIC_VIBESTRAL_WORKSPACES_DIR AGENTIC_OPENHANDS_WORKSPACES_DIR AGENTIC_COMPOSE_PROJECT AGENTIC_NETWORK AGENTIC_LLM_NETWORK AGENTIC_EGRESS_NETWORK AGENTIC_DOCKER_USER_SOURCE_NETWORKS AGENTIC_DOCKER_USER_CHAIN
export AGENTIC_COMPOSE_DIR AGENTIC_TEST_DIR
export AGENTIC_AGENT_BASE_BUILD_CONTEXT AGENTIC_AGENT_BASE_DOCKERFILE AGENTIC_AGENT_BASE_IMAGE
export AGENTIC_AGENT_CLI_INSTALL_MODE AGENTIC_AGENT_NO_NEW_PRIVILEGES
export AGENTIC_CODEX_CLI_NPM_SPEC AGENTIC_CLAUDE_CODE_NPM_SPEC AGENTIC_OPENCODE_NPM_SPEC AGENTIC_PI_CODING_AGENT_NPM_SPEC
export AGENTIC_OPENHANDS_INSTALL_SCRIPT AGENTIC_OPENCLAW_INSTALL_CLI_SCRIPT AGENTIC_OPENCLAW_INSTALL_VERSION AGENTIC_VIBE_INSTALL_SCRIPT
export AGENT_RUNTIME_UID AGENT_RUNTIME_GID
export QDRANT_CONTAINER_USER GATE_CONTAINER_USER OLLAMA_CONTAINER_USER TRTLLM_CONTAINER_USER
export PROMETHEUS_CONTAINER_USER GRAFANA_CONTAINER_USER LOKI_CONTAINER_USER PROMTAIL_CONTAINER_USER
export AGENTIC_OLLAMA_MODELS_LINK OLLAMA_MODELS_DIR OLLAMA_CONTAINER_MODELS_PATH OLLAMA_MODELS_MOUNT_MODE
export AGENTIC_DEFAULT_MODEL AGENTIC_DEFAULT_MODEL_CONTEXT_WINDOW AGENTIC_GOOSE_CONTEXT_LIMIT OLLAMA_PRELOAD_GENERATE_MODEL OLLAMA_PRELOAD_EMBED_MODEL OLLAMA_MODEL_STORE_BUDGET_GB RAG_EMBED_MODEL OLLAMA_CONTEXT_LENGTH
export AGENTIC_LLM_MODE GATE_ENABLE_TEST_MODE
export AGENTIC_OPENAI_DAILY_TOKENS AGENTIC_OPENAI_MONTHLY_TOKENS AGENTIC_OPENAI_DAILY_REQUESTS AGENTIC_OPENAI_MONTHLY_REQUESTS
export AGENTIC_OPENROUTER_DAILY_TOKENS AGENTIC_OPENROUTER_MONTHLY_TOKENS AGENTIC_OPENROUTER_DAILY_REQUESTS AGENTIC_OPENROUTER_MONTHLY_REQUESTS
export GATE_MCP_RATE_LIMIT_RPS GATE_MCP_RATE_LIMIT_BURST GATE_MCP_HTTP_TIMEOUT_SEC GATE_MCP_ALLOWED_MODEL_REGEX
export PROMTAIL_DOCKER_CONTAINERS_HOST_PATH PROMTAIL_HOST_LOG_PATH
export NODE_EXPORTER_HOST_ROOT_PATH CADVISOR_HOST_ROOT_PATH CADVISOR_DOCKER_LIB_HOST_PATH CADVISOR_SYS_HOST_PATH CADVISOR_DEV_DISK_HOST_PATH
export AGENTIC_LIMIT_DEFAULT_CPUS AGENTIC_LIMIT_DEFAULT_MEM
export AGENTIC_LIMIT_CORE_CPUS AGENTIC_LIMIT_CORE_MEM AGENTIC_LIMIT_OLLAMA_MEM AGENTIC_LIMIT_AGENTS_CPUS AGENTIC_LIMIT_AGENTS_MEM
export AGENTIC_LIMIT_UI_CPUS AGENTIC_LIMIT_UI_MEM AGENTIC_LIMIT_OBS_CPUS AGENTIC_LIMIT_OBS_MEM
export AGENTIC_LIMIT_RAG_CPUS AGENTIC_LIMIT_RAG_MEM AGENTIC_LIMIT_OPTIONAL_CPUS AGENTIC_LIMIT_OPTIONAL_MEM
export AGENTIC_LIMIT_OPENHANDS_MEM AGENTIC_LIMIT_COMFYUI_MEM
export AGENTIC_SKIP_DOCKER_USER_APPLY AGENTIC_SKIP_DOCKER_USER_CHECK AGENTIC_SKIP_DOCTOR_PROXY_CHECK
