#!/usr/bin/env bash

agentic_repo_root() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "${script_dir}/../.." && pwd
}

AGENTIC_REPO_ROOT="$(agentic_repo_root)"
AGENTIC_PROFILE="${AGENTIC_PROFILE:-strict-prod}"

case "${AGENTIC_PROFILE}" in
  strict-prod|rootless-dev)
    ;;
  *)
    echo "ERROR: invalid AGENTIC_PROFILE='${AGENTIC_PROFILE}' (expected strict-prod or rootless-dev)" >&2
    return 1 2>/dev/null || exit 1
    ;;
esac

if [[ "${AGENTIC_PROFILE}" == "rootless-dev" ]]; then
  AGENTIC_ROOT="${AGENTIC_ROOT:-${HOME}/.local/share/agentic}"
  AGENTIC_COMPOSE_PROJECT="${AGENTIC_COMPOSE_PROJECT:-agentic-dev}"
  AGENTIC_NETWORK="${AGENTIC_NETWORK:-agentic-dev}"
  AGENTIC_LLM_NETWORK="${AGENTIC_LLM_NETWORK:-agentic-dev-llm}"
  AGENTIC_EGRESS_NETWORK="${AGENTIC_EGRESS_NETWORK:-agentic-dev-egress}"
  AGENTIC_DOCKER_USER_CHAIN="${AGENTIC_DOCKER_USER_CHAIN:-AGENTIC-DOCKER-USER}"
  AGENT_RUNTIME_UID="${AGENT_RUNTIME_UID:-$(id -u)}"
  AGENT_RUNTIME_GID="${AGENT_RUNTIME_GID:-$(id -g)}"
  QDRANT_CONTAINER_USER="${QDRANT_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GATE_CONTAINER_USER="${GATE_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  AGENTIC_OLLAMA_MODELS_LINK="${AGENTIC_OLLAMA_MODELS_LINK:-${AGENTIC_REPO_ROOT}/.runtime/ollama-models}"
  OLLAMA_CONTAINER_USER="${OLLAMA_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  PROMETHEUS_CONTAINER_USER="${PROMETHEUS_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  GRAFANA_CONTAINER_USER="${GRAFANA_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  LOKI_CONTAINER_USER="${LOKI_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  PROMTAIL_CONTAINER_USER="${PROMTAIL_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"
  TRTLLM_CONTAINER_USER="${TRTLLM_CONTAINER_USER:-${AGENT_RUNTIME_UID}:${AGENT_RUNTIME_GID}}"

  AGENTIC_SKIP_DOCKER_USER_APPLY="${AGENTIC_SKIP_DOCKER_USER_APPLY:-1}"
  AGENTIC_SKIP_DOCKER_USER_CHECK="${AGENTIC_SKIP_DOCKER_USER_CHECK:-1}"
  AGENTIC_SKIP_DOCTOR_PROXY_CHECK="${AGENTIC_SKIP_DOCTOR_PROXY_CHECK:-1}"
else
  AGENTIC_ROOT="${AGENTIC_ROOT:-/srv/agentic}"
  AGENTIC_COMPOSE_PROJECT="${AGENTIC_COMPOSE_PROJECT:-agentic}"
  AGENTIC_NETWORK="${AGENTIC_NETWORK:-agentic}"
  AGENTIC_LLM_NETWORK="${AGENTIC_LLM_NETWORK:-agentic-llm}"
  AGENTIC_EGRESS_NETWORK="${AGENTIC_EGRESS_NETWORK:-agentic-egress}"
  AGENTIC_DOCKER_USER_CHAIN="${AGENTIC_DOCKER_USER_CHAIN:-AGENTIC-DOCKER-USER}"
  AGENT_RUNTIME_UID="${AGENT_RUNTIME_UID:-1000}"
  AGENT_RUNTIME_GID="${AGENT_RUNTIME_GID:-1000}"
  QDRANT_CONTAINER_USER="${QDRANT_CONTAINER_USER:-0:0}"
  GATE_CONTAINER_USER="${GATE_CONTAINER_USER:-0:0}"
  AGENTIC_OLLAMA_MODELS_LINK="${AGENTIC_OLLAMA_MODELS_LINK:-${AGENTIC_REPO_ROOT}/.runtime/ollama-models}"
  OLLAMA_CONTAINER_USER="${OLLAMA_CONTAINER_USER:-0:0}"
  PROMETHEUS_CONTAINER_USER="${PROMETHEUS_CONTAINER_USER:-0:0}"
  GRAFANA_CONTAINER_USER="${GRAFANA_CONTAINER_USER:-472:472}"
  LOKI_CONTAINER_USER="${LOKI_CONTAINER_USER:-0:0}"
  PROMTAIL_CONTAINER_USER="${PROMTAIL_CONTAINER_USER:-0:0}"
  TRTLLM_CONTAINER_USER="${TRTLLM_CONTAINER_USER:-0:0}"
fi

AGENTIC_COMPOSE_DIR="${AGENTIC_COMPOSE_DIR:-${AGENTIC_REPO_ROOT}/compose}"
AGENTIC_TEST_DIR="${AGENTIC_TEST_DIR:-${AGENTIC_REPO_ROOT}/tests}"

if [[ "${AGENTIC_PROFILE}" == "rootless-dev" ]]; then
  OLLAMA_MODELS_DIR="${OLLAMA_MODELS_DIR:-${AGENTIC_OLLAMA_MODELS_LINK}}"
  OLLAMA_CONTAINER_MODELS_PATH="${OLLAMA_CONTAINER_MODELS_PATH:-/tmp/ollama/models}"
else
  OLLAMA_MODELS_DIR="${OLLAMA_MODELS_DIR:-${AGENTIC_ROOT}/ollama/models}"
  OLLAMA_CONTAINER_MODELS_PATH="${OLLAMA_CONTAINER_MODELS_PATH:-/root/.ollama/models}"
fi
OLLAMA_MODELS_MOUNT_MODE="${OLLAMA_MODELS_MOUNT_MODE:-rw}"
OLLAMA_PRELOAD_GENERATE_MODEL="${OLLAMA_PRELOAD_GENERATE_MODEL:-qwen3:0.6b}"
OLLAMA_PRELOAD_EMBED_MODEL="${OLLAMA_PRELOAD_EMBED_MODEL:-qwen3-embedding:0.6b}"
OLLAMA_MODEL_STORE_BUDGET_GB="${OLLAMA_MODEL_STORE_BUDGET_GB:-12}"
RAG_EMBED_MODEL="${RAG_EMBED_MODEL:-qwen3-embedding:0.6b}"
PROMTAIL_DOCKER_CONTAINERS_HOST_PATH="${PROMTAIL_DOCKER_CONTAINERS_HOST_PATH:-/var/lib/docker/containers}"
PROMTAIL_HOST_LOG_PATH="${PROMTAIL_HOST_LOG_PATH:-/var/log}"
NODE_EXPORTER_HOST_ROOT_PATH="${NODE_EXPORTER_HOST_ROOT_PATH:-/}"
CADVISOR_HOST_ROOT_PATH="${CADVISOR_HOST_ROOT_PATH:-/}"
CADVISOR_DOCKER_LIB_HOST_PATH="${CADVISOR_DOCKER_LIB_HOST_PATH:-/var/lib/docker}"
CADVISOR_SYS_HOST_PATH="${CADVISOR_SYS_HOST_PATH:-/sys}"
CADVISOR_DEV_DISK_HOST_PATH="${CADVISOR_DEV_DISK_HOST_PATH:-/dev/disk}"

export AGENTIC_REPO_ROOT AGENTIC_PROFILE
export AGENTIC_ROOT AGENTIC_COMPOSE_PROJECT AGENTIC_NETWORK AGENTIC_LLM_NETWORK AGENTIC_EGRESS_NETWORK AGENTIC_DOCKER_USER_CHAIN
export AGENTIC_COMPOSE_DIR AGENTIC_TEST_DIR
export AGENT_RUNTIME_UID AGENT_RUNTIME_GID
export QDRANT_CONTAINER_USER GATE_CONTAINER_USER OLLAMA_CONTAINER_USER TRTLLM_CONTAINER_USER
export PROMETHEUS_CONTAINER_USER GRAFANA_CONTAINER_USER LOKI_CONTAINER_USER PROMTAIL_CONTAINER_USER
export AGENTIC_OLLAMA_MODELS_LINK OLLAMA_MODELS_DIR OLLAMA_CONTAINER_MODELS_PATH OLLAMA_MODELS_MOUNT_MODE
export OLLAMA_PRELOAD_GENERATE_MODEL OLLAMA_PRELOAD_EMBED_MODEL OLLAMA_MODEL_STORE_BUDGET_GB RAG_EMBED_MODEL
export PROMTAIL_DOCKER_CONTAINERS_HOST_PATH PROMTAIL_HOST_LOG_PATH
export NODE_EXPORTER_HOST_ROOT_PATH CADVISOR_HOST_ROOT_PATH CADVISOR_DOCKER_LIB_HOST_PATH CADVISOR_SYS_HOST_PATH CADVISOR_DEV_DISK_HOST_PATH
export AGENTIC_SKIP_DOCKER_USER_APPLY AGENTIC_SKIP_DOCKER_USER_CHECK AGENTIC_SKIP_DOCTOR_PROXY_CHECK
