server:
  chroot: ""
  username: ""
  directory: "/etc/unbound"
  pidfile: "/tmp/unbound.pid"
  interface: 0.0.0.0@53
  interface: ::0@53
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 0.0.0.0/0 allow
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  qname-minimisation: yes
  prefetch: yes
  verbosity: 1

forward-zone:
  name: "."
  forward-first: no
  forward-addr: 1.1.1.1@53
  forward-addr: 9.9.9.9@53
